landing-ai/vision-agent-tools

- Makefile
- docs/florencev2-qa.md
- poetry.lock
- pyproject.toml
- tests/tools/test_florencev2_qa.py
- vision_agent_tools/helpers/roberta_qa.py
- vision_agent_tools/tools/florencev2_qa.py
Description
---
* Add [`RobertaQA`](https://huggingface.co/deepset/roberta-base-squad2) model as an auxiliary QA model for FlorenceV2 image QA
* Add `FlorenceQA` model to do QA on images
* Add test
* Add documentation
> feat: add roberta and florence-qa models

- docs/nshot_counting.md
- tests/tools/test_loca.py
- vision_agent_tools/tools/nshot_counting.py
Description
---
* Add LOCA n-shot model weights.
> refactor: change loca zero-shot to n-shot counting

- vision_agent_tools/tools/owlv2.py
Description
---
This PR adds some improvements to the Owlv2 model such us:
* Change from base more to the larger model
* Load model to the correct `device`
* Use post_process_object_detection to use threshold instead of manually doing it
> chore: use larger model for owlv2

- vision_agent_tools/tools/florencev2.py
Description
---
* Update Florence2 model to be the larger model.
> chore: update florence2 model to be the larger model

- .github/workflows/unit-tests.yml
It is impossible to publish with git dependencies
> fix: revert pypi publish

- .github/workflows/unit-tests.yml
- README.md
Add unit tests on main push and add badge on readme
> docs: add unittests on main push and badge

- tests/models/test_internlm_xcomposer2.py
- vision_agent_tools/models/internlm_xcomposer2.py
Description
---
* Allow IXC2 model to handle video chunk analysis.
> feat: update ixc2 model to handle video chunks

- tests/models/test_internlm_xcomposer2.py
- vision_agent_tools/models/internlm_xcomposer2.py
Received feedback about API so changing to chunk_length
> feat: change to n_chunks to chunk_length

- README.md
- tests/tools/test_shared_model_manager.py
- vision_agent_tools/models/florencev2.py
- vision_agent_tools/models/nshot_counting.py
- vision_agent_tools/shared_types.py
- vision_agent_tools/tools/shared_model_manager.py
So we can use fetch the model upon request in the flight.
> feat: gpu pool to swap model

- .devcontainer.json
- .gitignore
- Makefile
- README.md
- poetry.lock
- pyproject.toml
- scripts/install.sh
- tests/tools/test_shared_model_manager.py
- tests/tools/test_text_to_object_detection.py
- vision_agent_tools/models/florencev2.py
- vision_agent_tools/models/owlv2.py
- vision_agent_tools/tools/text_to_object_detection.py
Also schemalized the output to connect the pieces.
> feat: add florencev2 to txt2od

- vision_agent_tools/models/florence2_sam2.py
Description
---
* We are having some class overlap problems on the predictions.
* This PR introduces a dummy non-max suppression function ("dummy" in the sense that we don't really have score values) 
Test
---
Inference before NMS, we can see that the surfer at the right most part of the video has two ids, id:2 for shark and id:3 for surfer.
https://github.com/user-attachments/assets/da7b2b71-687a-4b5f-a2bd-5ed4e89acdf8
By applying the dummy NMS function, we can see that we remove the prediction overlaps and consistently predicts the class for the object that we are tracking. NOTE: if FlorenceV2 predicts the wrong classes at the beginning of the video, the error will propagate throughout.
https://github.com/user-attachments/assets/3da552d3-57fe-4f34-a66b-ef6b430afb38
> feat: add nms to Florence2Sam2

- tests/tools/test_shared_model_manager.py
- vision_agent_tools/tools/shared_model_manager.py
Per convo with @hrnn and @Dayof , let's simplified and push off adopting async mode, until everything in the library have async option.
> chore: model manager in sync mode

- vision_agent_tools/shared_types.py
- vision_agent_tools/tools/shared_model_manager.py
- vision_agent_tools/tools/text_to_object_detection.py
In order to get end-to-end working.
> chore: txt-to-od-can-swtich-device

- tests/models/test_florencev2.py
- vision_agent_tools/models/florencev2.py
- Introduced a `batch_size` parameter (defaulting to `5`) in the `__call__` method.
- Modified image and video processing logic to split inputs into batches of size `batch_size`.
> refactor: florencev2 batch size

- tests/models/test_florence2_sam2.py
- tests/models/test_florencev2.py
- tests/tools/test_shared_model_manager.py
- tests/tools/test_text_to_instance_segmentation.py
- vision_agent_tools/models/depth_anything_v2.py
- vision_agent_tools/models/florence2_sam2.py
- vision_agent_tools/models/florencev2.py
- vision_agent_tools/models/nshot_counting.py
- vision_agent_tools/models/owlv2.py
- vision_agent_tools/models/qr_reader.py
- vision_agent_tools/models/utils.py
- vision_agent_tools/shared_types.py
- vision_agent_tools/tools/shared_model_manager.py
- vision_agent_tools/tools/text_to_instance_segmentation.py
- vision_agent_tools/tools/text_to_object_detection.py
Description
---
* Refactor Florence2Sam2 NMS
* Move the dummy NMS to Florencev2
* Unify BoundingBox format among models
* Add util functions for calculating bbox and mask IoU
* Add util functions to format Florecev2 Bbox predictions
* Fix linting on some files
* Add unit tests for nms_threshold on Florencev2 and Florence2Sam2 models
Tests
---
> refactor: Florence2Sam2 NMS and move it to Florencev2

- tests/tools/test_text_to_object_detection.py
- vision_agent_tools/tools/text_to_object_detection.py
Description
---
* The Florencev2 model task receiving the wrong task type value since it is ignoring the prompts of the objects to find on the images.
* This work fixes the task type in the FlorenceV2 model on the "Text to Object Detection" tool.
Tests
---
> fix: text to object detection tool predictions

- vision_agent_tools/models/florencev2.py
Handling out of memory error
Please review [ignoring whitespace changes](https://github.com/landing-ai/vision-agent-tools/pull/76/files?w=1)
> chore: handling out of memory for florencev2

- docs/qr_reader.md
- tests/models/test_florence2_sam2.py
- tests/tools/test_text_to_instance_segmentation.py
- tests/tools/test_text_to_object_detection.py
- vision_agent_tools/models/florence2_sam2.py
- vision_agent_tools/models/florencev2.py
- vision_agent_tools/models/nshot_counting.py
- vision_agent_tools/models/owlv2.py
- vision_agent_tools/models/qr_reader.py
- vision_agent_tools/models/utils.py
- vision_agent_tools/shared_types.py
- vision_agent_tools/tools/text_to_instance_segmentation.py
- vision_agent_tools/tools/text_to_object_detection.py
Description
---
* Unify the object detection return output for models and tools: Florencev2, Owlv2, Florence2Sam2, TextToObjectDetection
* Fix linting
* TODO: unify SAM2 model output
Tests
---
> chore: unify the object detection return output for models and tools

- tests/models/test_owlv2.py
- vision_agent_tools/models/owlv2.py
Description
---
* Fix owlv2 error when prompt is too large
Tests
---
> fix: owlv2 error when prompt is too large

- poetry.lock
- pyproject.toml
Exposing `sam2` model, so it can be imported anywhere as single tool.
> feat: sam2 as extra

- vision_agent_tools/models/siglip.py
> feat: improve siglip weights
